### ISSUE TITLE
Execution output does not support ANSI codes 

### ISSUE THREAD

**Issue by jgraichen** [openHPI/codeocean#222]
Program run in CodeOcean are run in a TTY and are announcing color support (`tput colors` returns `8`) but the output does not render/stripe such codes. Programs checking and using color cores produce hard to read output such as:

```
[1mTraceback[m (most recent call last):
	2: from tasks.rb:4:in `<main>'
	1: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': [1mcannot load such file -- time_trackerd ([1;4mLoadError[m[1m)
[m
```

Best would be if CO would render program output with an actual terminal emulator (such as xterm.js) to support coloring and more.

**Comment by jgraichen** [comment]
The behavior seems to differ between the main file execution mode and the user-defined test case execution mode. The second run mode (running the main file because of #220) does not set a `$TERM` variable:

```
StdErr: 
tput: No value for $TERM and no -T specified
```

The rendered output text also is not green but black.
