### ISSUE TITLE
NoMethodError: undefined method `check_uuid_url' for nil:NilClass

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeocean#496]
If a user tries to export an exercise without setting up a CodeHarbor link, the UUID check might fail.

---

Sentry Issue: [CODEOCEAN-9]

```
NoMethodError: undefined method `check_uuid_url' for nil:NilClass
  app/services/exercise_service/check_external.rb:34:in `connection'
    Faraday.new(url: @codeharbor_link.check_uuid_url) do |faraday|
  app/services/exercise_service/check_external.rb:11:in `execute'
    response = connection.post do |req|
  app/services/service_base.rb:5:in `call'
    new(*args).execute
  app/controllers/exercises_controller.rb:125:in `export_external_check'
    codeharbor_check = ExerciseService::CheckExternal.call(uuid: @exercise.uuid, codeharbor_link: current_user.codeharbor_link)
...
(90 additional frame(s) were not displayed)
```

**Comment by kkoehn** [comment]
This should not be an issue anymore. Users can't start the export without setting up the link before.
